### PR TITLE
Fix priority of application vs unary

### PR DESCRIPTION
**Pull request by aryx**
test plan:
make test

### CODE REVIEW

**Comment by aryx** [comment]
@tjdevries another one ...

**Comment by aryx** [comment]
without this code in std.jsonnet such as !std.isNumber(x) is parsed as   (!std.isNumber)(x)

**Comment by aryx** [comment]
ping @tjdevries

**Comment by aryx** [comment]
ping

**Comment by tjdevries** [comment]
Thanks!

**Pull request merged**
